### ISSUE TITLE
已添加的APP删除后, 添加APP闪退

### ISSUE THREAD

**Issue by yhx5768** [Septillion/KFMARK#99]
**Describe the bug**
已添加的APP删除后, 添加APP闪退

**To Reproduce**
1. 打开快否, 添加app ""
2. 点击启动, 并开始录制;
3. 点击停止录制, 并选择保存记录;
4. 将快否压后台, 卸载 ""
5. 返回快否, 测试列表里之前的APP名称变为 "阴阳师", 并且无图标, 点击运行/删除均无相应;
6. 点击添加游戏, 点击任意APP, 发生崩溃;

崩溃日志如下:
```
FATAL EXCEPTION: main
Process: com.af.benchaf, PID: 16843
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.zqb.baselibrary.util.util.AppUtils$AppInfo.getName()' on a null object reference
	at com.af.benchaf.test.ApplicationListActivity$MyViewHolder$1.onClick(ApplicationListActivity.java:322)
	at android.view.View.performClick(View.java:5664)
	at android.view.View$PerformClick.run(View.java:22429)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6390)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:983)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Smartphone (please complete the following information):**
 - Device: Meizu 15 plus
 - OS: Android 7.0
 - App Version: v1.5

**Comment by Onkar547** [comment]
I can't download KF MARK HOW TO DOWNLOAD
